name: meds_record
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter:
    sdk: flutter
  salomon_bottom_bar: ^3.3.2
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  encrypt: ^5.0.3
  firebase_storage: ^12.0.1
  pdf: ^3.10.8
  file_picker: ^8.0.4
  path_provider: ^2.1.3
  firebase_app_check: ^0.3.0+1
  flutter_pdfview: ^1.3.2
  crypto: ^3.0.3
  cryptography: ^2.7.0
  permission_handler: ^11.3.1
  device_info_plus: ^10.1.0
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_lints: 4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
